# Generated by Django 3.0.4 on 2021-07-13 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_gunmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunmen',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
