# Generated by Django 3.0.4 on 2021-07-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_gunmen'),
        ('attendance', '0002_auto_20210712_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='gunmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Gunmen'),
        ),
        migrations.DeleteModel(
            name='Gunmen',
        ),
    ]
