# Generated by Django 3.0.4 on 2021-07-19 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210715_1609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0005_custodian'),
        ('attendance', '0003_auto_20210712_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('entry_time', models.DateTimeField(default=datetime.datetime.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Branch')),
                ('custodian_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_1', to='vendors.Custodian')),
                ('custodian_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_2', to='vendors.Custodian')),
                ('custodian_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_3', to='vendors.Custodian')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vehicle')),
            ],
        ),
    ]
