# Generated by Django 3.0.4 on 2021-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
