# Generated by Django 3.0.4 on 2021-07-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_custodian'),
        ('attendance', '0006_auto_20210720_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='gunmen',
        ),
        migrations.AddField(
            model_name='attendance',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Custodian'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
