# Generated by Django 3.0.4 on 2021-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20210720_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='custodian_1_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='custodian_2_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='custodian_3_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
