# Generated by Django 3.0.4 on 2021-07-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20210720_1804'),
        ('attendance', '0007_auto_20210720_2300'),
    ]

    operations = [
    ]
