# Generated by Django 3.0.4 on 2021-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_merge_20210721_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_start',
            field=models.BooleanField(default=False),
        ),
    ]
